### ISSUE TITLE
Unexpected results of transforms on Image?

### ISSUE THREAD

**Issue by rbelew** [cduck/drawsvg#115]
I want to place a set of PNG images within an SVG.  I am doing this for a series of files with card images:

```
	pg = dw.Drawing(800, 1000, origin=(0, 0))
	
	cdFile = f'{cardName}.png'
	cdImg = dw.Image(x, y, cdwid, cdhgt, path=cdFile, embed=True, transform='rotate(90)') 
	pg.append(cdImg)
	...
```
	
modifying the `x,y` coordinates as I go along. The card image files are in a "portrait," vertical orientation.  

![clubs_4](https://github.com/cduck/drawsvg/assets/120920/7c068606-2372-4279-bc3a-e8e24ef00e2b)

With the rotation they're designed to fit nicely on a page.

But the resulting SVG file:

[page00-svg.txt](https://github.com/cduck/drawsvg/files/13747138/page00-svg.txt)

seems to be ignoring my `x,y` coordinate specs and the `transform='rotate(90)'`, as rendered by firefox (same with Chrome).

<img width="727" alt="page00-firefox" src="https://github.com/cduck/drawsvg/assets/120920/7d958c5d-9741-4d3f-99aa-ae653c771b74">

But here's another odd bit: I use a graphic editor called EazyDraw. When I open the same SVG file with it, it generates about what I had in mind, obeying the `x,y` coordinate layouts but NOT doing the transform, AND not obeying `preserveAspectRatio`, because I don't know where to do that with drawsvg?  

<img width="566" alt="page00-ez" src="https://github.com/cduck/drawsvg/assets/120920/50dc3d63-baf8-4335-b9d8-a07f57186585">

Any ideas as to why it EazyDraw would have this difference?

**Comment by rbelew** [comment]
ANother perhaps useful bit of background:  importing the SVG file above (built using drawsvg) with EazyDraw, then having EazyDraw export the result generates the attached file.

It is this file that firefox/chrome rendered in the two column format above.
[page00-ez-svg.txt](https://github.com/cduck/drawsvg/files/13774105/page00-ez-svg.txt)

**Comment by eazydave** [comment]
Short Answer: reverse width and height for images.

It may be a bug in EazyDraw; send the file to EazyDraw support. 

 But - I could not get either of your files to display in Safari, so there is some problem. I generally use Safari as the gold standard for the image's appearance.

 Examining the SVG content, the width and height values are reversed for the portrait PNG images. EazyDraw accepts your file and presents the stretched images. The reverse of width and height values gives a undistorted presentation of the images with EazyDraw.

**Comment by rbelew** [comment]
Hey @eazydave, thanks for bringing your expertise here!  

the width/height are reversed to conform to the `transform="rotate(90)"`.
my read of the SVG standard is that it is allowed on images, even in SVG1.1?

**Comment by cduck** [comment]
Thanks for the question @rbelew!  @eazydave I think you have the right idea so let me expand on that.

The key concept you missed here is that you are rotating around the origin (top-left corner in this case).  Before rotation, your image is in the middle of the canvas but after rotation it is far off the left side of the canvas.  Change this line of your code to see what I mean:

```python
pg = dw.Drawing(800*2, 1000*2, origin='center')
# ...
```

When I use `transform`, I typically set `x=0` and `y=0` so this doesn't happen and use `transform="translate(..., ...) rotate(...)"`.  This will rotate your card about its top-left corner *and then* translate it.  Alternatively, [specify the optional origin of rotation](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#rotate).

```python
pg = dw.Drawing(800*2, 1000*2, origin='center')

cdFile = f'{cardName}.png'
orig_width = 220
orig_height = 316
cdImg = dw.Image(
        0, 0, orig_width, orig_height, path=cdFile, embed=True,
        transform=f'translate({orig_height+x}, {y}) rotate(90)') 
pg.append(cdImg)
```

-----

If the cards seemed smaller than expected, that is because the x, y, width, and height you give are the bounding box that the image is centered within (before transformation!).  See [preserveAspectRatio](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio#image) if you want to stretch the image.

-----

Regarding EazyDraw, I don't know anything about it but, from the information you gave, it appears EazyDraw does not support the `transform` attribute (and does not display images with preserved aspect-ratio).  Notice that all the `transform`s are gone in the second file you posted.
