### ISSUE TITLE
make it possible to print the svg

### ISSUE THREAD

**Issue by tommycarstensen** [cduck/drawSvg#41]
It is possible to do `saveSvg()`. It would be great, if one could do `printSvg()` as well, so one has the option to append the svg to some already existing svg file.

**Comment by cduck** [comment]
I'm curious, what is the use case for appending an SVG?

**Comment by tommycarstensen** [comment]
I have a map to which I want to add arrows. My workaround was to write to an svg file to see the syntax and then append to the map svg.

**Comment by cduck** [comment]
OK.  Simply appending the output won't work because everything has to be between the original pair of `<svg></svg>` tags.

It sounds like you might be doing this manually, so `print(d.asSvg())` may do what you want.  Make sure none of the element `id`s conflict with the original SVG though.  You can use the `idPrefix` argument of `Drawing` to prevent conflicts.

If you instead want to cleanly embed the map in a drawSvg drawing, it's a bit involved but you can parse and embed it something like this: https://github.com/cduck/latextools/blob/e12c3bb3a58e03179623a544e289734157db3d77/latextools/convert.py#L208
