### ISSUE TITLE
Vertically inverted arcs

### ISSUE THREAD

**Issue by neago** [cduck/drawSvg#91]
After the flipping of the coordinate system in v2.0, I believe the y-coordinate signs in these two lines should be inverted - otherwise the angles are increased in clockwise direction. 

https://github.com/cduck/drawSvg/blob/1cb673ad81d221ec8af6706b3d19faa808d03a5a/drawsvg/elements.py#L556-L557

**Comment by cduck** [comment]
Thanks for opening an issue!  This is intentional to be consistent with how the SVG rotate transform interprets angles.  Unfortunately, version 2 had to break this one way or another.  Now clockwise (cw) means rotating from +x towards +y and angles also increase from +x towards +y.  I believe this is consistent with how the SVG spec handles clockwise and angle parameters (let me know if you disagree).  This will hopefully make things easier going forward but converting is a bit awkward.

I hope it is not too much inconvenience for you to negate your angles and invert the cw flag when you upgrade.

**Comment by neago** [comment]
Ah, makes sense! But an annoying convention.
I did figure out after a couple of trials to fix it exactly as you suggested.
Thanks! Also for this useful little library!

I was a little surprised yesterday when my figure was suddenly inverted in many different ways :smile:  But didn't take too long figuring out where to change signs and offsets. I think it will be much easier going forward with the new coordinate system - apart from the annoying angles.
